## Wireless Indoor Localization

### Imports

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.0


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import deep_learning_helper as dl_helper

### Data

In [4]:
df = pd.read_csv('wifi_localization.txt', delimiter='\t', header=None, names=pd.Series(['Wifi-1', 'Wifi-2', 'Wifi-3', 'Wifi-4', 'Wifi-5', 'Wifi-6', 'Wifi-7', 'Room']))
df.head()

Wifi-1  Wifi-2  Wifi-3  Wifi-4  Wifi-5  Wifi-6  Wifi-7  Room
0     -64     -56     -61     -66     -71     -82     -81     1
1     -68     -57     -61     -65     -71     -85     -85     1
2     -63     -60     -60     -67     -76     -85     -84     1
3     -61     -60     -68     -62     -77     -90     -80     1
4     -63     -65     -60     -63     -77     -81     -87     1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Wifi-1  2000 non-null   int64
 1   Wifi-2  2000 non-null   int64
 2   Wifi-3  2000 non-null   int64
 3   Wifi-4  2000 non-null   int64
 4   Wifi-5  2000 non-null   int64
 5   Wifi-6  2000 non-null   int64
 6   Wifi-7  2000 non-null   int64
 7   Room    2000 non-null   int64
dtypes: int64(8)
memory usage: 125.1 KB


In [6]:
df.describe()

Wifi-1       Wifi-2       Wifi-3       Wifi-4       Wifi-5  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    -52.330500   -55.623500   -54.964000   -53.566500   -62.640500   
std      11.321677     3.417688     5.316186    11.471982     9.105093   
min     -74.000000   -74.000000   -73.000000   -77.000000   -89.000000   
25%     -61.000000   -58.000000   -58.000000   -63.000000   -69.000000   
50%     -55.000000   -56.000000   -55.000000   -56.000000   -64.000000   
75%     -46.000000   -53.000000   -51.000000   -46.000000   -56.000000   
max     -10.000000   -45.000000   -40.000000   -11.000000   -36.000000   

            Wifi-6       Wifi-7         Room  
count  2000.000000  2000.000000  2000.000000  
mean    -80.985000   -81.726500     2.500000  
std       6.516672     6.519812     1.118314  
min     -97.000000   -98.000000     1.000000  
25%     -86.000000   -87.000000     1.750000  
50%     -82.000000   -83.000000     2.500000  
75%     -77.000000   -78.000000     3.250000  
max     -61.000000   -63.000000     4.000000

### Preprocess Data

In [7]:
X = df.drop('Room', axis=1)
y = df['Room']

In [8]:
X.head()

Wifi-1  Wifi-2  Wifi-3  Wifi-4  Wifi-5  Wifi-6  Wifi-7
0     -64     -56     -61     -66     -71     -82     -81
1     -68     -57     -61     -65     -71     -85     -85
2     -63     -60     -60     -67     -76     -85     -84
3     -61     -60     -68     -62     -77     -90     -80
4     -63     -65     -60     -63     -77     -81     -87

In [9]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Room, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [12]:
X_train.head()

Wifi-1  Wifi-2  Wifi-3  Wifi-4  Wifi-5  Wifi-6  Wifi-7
968     -37     -54     -47     -36     -63     -70     -70
240     -58     -59     -59     -65     -65     -82     -94
819     -42     -54     -58     -41     -63     -75     -78
692     -37     -56     -57     -39     -61     -72     -74
420     -64     -57     -63     -59     -68     -82     -83

In [13]:
y_train.head()

968    2
240    1
819    2
692    2
420    1
Name: Room, dtype: int64

### ML Algorithms

#### Linear SVC

In [14]:
from sklearn.svm import LinearSVC

In [15]:
model1 = LinearSVC()
model1.fit(X_train, y_train)

/home/iniyankanmani/Documents/envs/ml/lib/python3.8/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [16]:
model1.score(X_test, y_test)

0.955

In [17]:
y_pred_1 = pd.Series(model1.predict(X_test))
y_pred_1[:5]

0    4
1    1
2    3
3    2
4    3
dtype: int64

In [18]:
model1_results = dl_helper.calculate_classification_metrics(y_test, y_pred_1, average='micro', print_values=True)

Accuracy:               0.955
Precision:              0.955
Recall:                 0.955
F1                      0.955
Confusion Matrix:      
[[100   0   2   2]
 [  0  92   3   0]
 [  0   8  77   3]
 [  0   0   0 113]]
Classification Report: 
              precision    recall  f1-score   support

           1       1.00      0.96      0.98       104
           2       0.92      0.97      0.94        95
           3       0.94      0.88      0.91        88
           4       0.96      1.00      0.98       113

    accuracy                           0.95       400
   macro avg       0.95      0.95      0.95       400
weighted avg       0.96      0.95      0.95       400



#### KNeighbors

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
model2 = KNeighborsClassifier()
model2.fit(X_train, y_train)

KNeighborsClassifier()

In [22]:
y_pred_2 = pd.Series(model2.predict(X_test))
y_pred_2[:5]

0    4
1    1
2    3
3    2
4    3
dtype: int64

In [23]:
model2_results = dl_helper.calculate_classification_metrics(y_test, y_pred_2, 'micro', print_values=True)

Accuracy:               0.9825
Precision:              0.9825
Recall:                 0.9825
F1                      0.9825
Confusion Matrix:      
[[104   0   0   0]
 [  0  89   6   0]
 [  0   0  88   0]
 [  1   0   0 112]]
Classification Report: 
              precision    recall  f1-score   support

           1       0.99      1.00      1.00       104
           2       1.00      0.94      0.97        95
           3       0.94      1.00      0.97        88
           4       1.00      0.99      1.00       113

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg       0.98      0.98      0.98       400



#### SVC

In [24]:
from sklearn.svm import SVC

In [27]:
model3 = SVC()
model3.fit(X_train, y_train)

SVC()

In [28]:
y_pred_3 = pd.Series(model3.predict(X_test))
y_pred_3[:5]

0    4
1    1
2    3
3    2
4    3
dtype: int64

In [29]:
model3_results = dl_helper.calculate_classification_metrics(y_test, y_pred_3, 'micro', print_values=True)

Accuracy:               0.98
Precision:              0.98
Recall:                 0.98
F1                      0.98
Confusion Matrix:      
[[104   0   0   0]
 [  0  89   6   0]
 [  0   0  87   1]
 [  1   0   0 112]]
Classification Report: 
              precision    recall  f1-score   support

           1       0.99      1.00      1.00       104
           2       1.00      0.94      0.97        95
           3       0.94      0.99      0.96        88
           4       0.99      0.99      0.99       113

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg       0.98      0.98      0.98       400

